"""relation stuff

Revision ID: e4298c5d6e6a
Revises: fe0111accf36
Create Date: 2025-12-25 12:32:32.087442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4298c5d6e6a'
down_revision = 'fe0111accf36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('photo_product_id_fkey'), 'photo', type_='foreignkey')
    op.create_foreign_key(None, 'photo', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('uq_product_url_idx'), table_name='product')
    op.drop_constraint(op.f('property_product_id_fkey'), 'property', type_='foreignkey')
    op.create_foreign_key(None, 'property', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.create_foreign_key(op.f('property_product_id_fkey'), 'property', 'product', ['product_id'], ['id'])
    op.create_index(op.f('uq_product_url_idx'), 'product', ['url'], unique=True)
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.create_foreign_key(op.f('photo_product_id_fkey'), 'photo', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
