"""init

Revision ID: fe0111accf36
Revises:
Create Date: 2025-12-25 12:15:09.749887

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe0111accf36"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.Column("url", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", name="uq_product_url"),
    )
    op.create_table(
        "photo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "property",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("weight", sa.TEXT(), nullable=True),
        sa.Column("work_time", sa.TEXT(), nullable=True),
        sa.Column("charge_time", sa.TEXT(), nullable=True),
        sa.Column("lenght_of_work", sa.TEXT(), nullable=True),
        sa.Column("battery_capacity", sa.TEXT(), nullable=True),
        sa.Column("voltage", sa.TEXT(), nullable=True),
        sa.Column("model", sa.TEXT(), nullable=True),
        sa.Column("material", sa.TEXT(), nullable=True),
        sa.Column("power", sa.TEXT(), nullable=True),
        sa.Column("motor", sa.TEXT(), nullable=True),
        sa.Column("manufactured", sa.TEXT(), nullable=True),
        sa.Column("warranty", sa.TEXT(), nullable=True),
        sa.Column("rpm", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("property")
    op.drop_table("photo")
    op.drop_table("product")
    # ### end Alembic commands ###
